workaround for issue with spreadsheet gem when mathn lib required
$ irb
>> require 'mathn'
=> true
>> require 'spreadsheet'
=> true
>> Spreadsheet.open('/path/to/file.xls')
TypeError: no implicit conversion from nil to integer
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/ranges_io.rb:165:in `seek'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/ranges_io.rb:165:in `read'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/ranges_io.rb:164:in `loop'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/ranges_io.rb:164:in `read'
	from (irb):3:in `to_proc'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/ranges_io.rb:72:in `open'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:504:in `open'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:508:in `read'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:122:in `load'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:77:in `initialize'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:83:in `new'
	from /usr/local/Cellar/gems/1.8/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:83:in `open'
	from /usr/local/Cellar/gems/1.8/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/reader.rb:1130:in `setup'
	from /usr/local/Cellar/gems/1.8/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/reader.rb:121:in `read'
	from /usr/local/Cellar/gems/1.8/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/workbook.rb:32:in `open'
	from /usr/local/Cellar/gems/1.8/gems/spreadsheet-0.6.4.1/lib/spreadsheet.rb:62:in `open'
	from /usr/local/Cellar/gems/1.8/gems/spreadsheet-0.6.4.1/lib/spreadsheet.rb:68:in `open'
	from (irb):3>> 

I'm guessing this may be due to this bug in mathn: http://redmine.ruby-lang.org/issues/show/2121